name: mts3-mcte-team-project-energy-g1
services:
  backend:
    build:
      context: C:\Users\rodri\source\25-26\teamproject\MTS3-MCTE-Team-Project-Energy-G1
      dockerfile: apps/backend/Dockerfile
      target: production
    depends_on:
      influxdb:
        condition: service_healthy
        required: true
      influxdb-init:
        condition: service_completed_successfully
        required: true
      redis:
        condition: service_healthy
        required: true
    environment:
      AUTH_VERIFY_AUD: "false"
      CORS_ORIGINS: http://localhost:3000,http://localhost:8080,http://localhost:5173
      ENV: dev
      INFLUX_BUCKET_PRED: predictions
      INFLUX_ORG: energy-monitor
      INFLUX_TOKEN: admin-token
      INFLUX_URL: http://influxdb:8086
      PIPELINE_ENQUEUE_ENABLED: "true"
      PIPELINE_ROLLING_WINDOW_SIZE: "4096"
      PIPELINE_WORKER_IN_API_ENABLED: "false"
      PORT: "8000"
      RATE_LIMIT_PER_IP: 1200/minute
      REDIS_URL: redis://redis:6379/0
      SUPABASE_ANON_KEY: sb_publishable_I3L-MhSwOX8vfWt91ppHOg_uu18TByg
      SUPABASE_JWT_SECRET: fwW/ym5QYgFMLNeqwQARAp9UjAAtFT4HMSEZLnsZVlz3Gd5YI7r1quoOgfotwupoIABmYuxMkRbIHZF3ioLT9Q==
      SUPABASE_PUBLISHABLE_KEY: sb_publishable_I3L-MhSwOX8vfWt91ppHOg_uu18TByg
      SUPABASE_SECRET_KEY: sb_secret_rvzGmMDdNFtl5hSNHdbA8Q_Sqprvb-r
      SUPABASE_URL: https://bhdcbvruzvhmcogxfkil.supabase.co
    healthcheck:
      test:
        - CMD
        - curl
        - -sf
        - http://localhost:8000/live
      timeout: 5s
      interval: 10s
      retries: 3
      start_period: 15s
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8000
        published: "8000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: C:\Users\rodri\source\25-26\teamproject\MTS3-MCTE-Team-Project-Energy-G1\apps\backend\models
        target: /app/models
        read_only: true
        bind: {}
      - type: bind
        source: C:\Users\rodri\source\25-26\teamproject\MTS3-MCTE-Team-Project-Energy-G1\apps\backend\data
        target: /app/data
        read_only: true
        bind: {}
      - type: bind
        source: C:\Users\rodri\source\25-26\teamproject\MTS3-MCTE-Team-Project-Energy-G1\apps\backend\src
        target: /app/src
        read_only: true
        bind: {}
  influxdb:
    environment:
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin-token
      DOCKER_INFLUXDB_INIT_BUCKET: predictions
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: energy-monitor
      DOCKER_INFLUXDB_INIT_PASSWORD: admin12345
      DOCKER_INFLUXDB_INIT_USERNAME: admin
    healthcheck:
      test:
        - CMD
        - influx
        - ping
        - --host
        - http://localhost:8086
      timeout: 5s
      interval: 10s
      retries: 5
    image: influxdb:2.8
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8086
        published: "8086"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: influxdb-data
        target: /var/lib/influxdb2
        volume: {}
      - type: volume
        source: influxdb-config
        target: /etc/influxdb2
        volume: {}
  influxdb-init:
    command:
      - set
      - -euo
      - pipefail
      - echo
      - Waiting for InfluxDB to be ready...
      - influx
      - ping
      - --host
      - $$INFLUX_HOST
      - echo
      - Ensuring buckets exist...
      - if
      - influx
      - bucket
      - list
      - --host
      - $$INFLUX_HOST
      - --token
      - $$INFLUX_TOKEN
      - --org
      - $$INFLUX_ORG
    depends_on:
      influxdb:
        condition: service_healthy
        required: true
    entrypoint:
      - /bin/sh
      - -c
    environment:
      INFLUX_BUCKET_PRED: predictions
      INFLUX_HOST: http://influxdb:8086
      INFLUX_ORG: energy-monitor
      INFLUX_TOKEN: admin-token
    image: influxdb:2.8
    networks:
      default: null
    restart: "no"
  redis:
    command:
      - redis-server
      - --appendonly
      - "yes"
    container_name: nilm-redis
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
      interval: 10s
      retries: 5
    image: redis:7-alpine
    networks:
      default: null
    ports:
      - mode: ingress
        target: 6379
        published: "6379"
        protocol: tcp
    volumes:
      - type: volume
        source: redis-data
        target: /data
        volume: {}
  simulator:
    build:
      context: C:\Users\rodri\source\25-26\teamproject\MTS3-MCTE-Team-Project-Energy-G1
      dockerfile: apps/backend/Dockerfile.simulator
    depends_on:
      backend:
        condition: service_healthy
        required: true
      worker:
        condition: service_started
        required: true
    environment:
      BACKEND_URL: http://backend:8000
      BUILDING_ID: building-1
      DATA_POWER_COLUMN: aggregate
      PARQUET_PATH: /app/data/simulation_data.parquet
      SIM_DURATION_SECONDS: "0"
      SIM_SPEEDUP: "1"
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: C:\Users\rodri\source\25-26\teamproject\MTS3-MCTE-Team-Project-Energy-G1\apps\backend\data
        target: /app/data
        read_only: true
        bind: {}
  worker:
    build:
      context: C:\Users\rodri\source\25-26\teamproject\MTS3-MCTE-Team-Project-Energy-G1
      dockerfile: apps/backend/Dockerfile.worker
    depends_on:
      influxdb:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
    environment:
      ENV: dev
      INFLUX_BUCKET_PRED: predictions
      INFLUX_ORG: energy-monitor
      INFLUX_TOKEN: admin-token
      INFLUX_URL: http://influxdb:8086
      MODEL_REGISTRY_PATH: /app/models/registry.json
      MODELS_DIR: /app/models
      PIPELINE_ENQUEUE_ENABLED: "true"
      PIPELINE_ROLLING_WINDOW_SIZE: "4096"
      REDIS_CONSUMER_GROUP: nilm-infer-dev
      REDIS_STREAM_KEY: nilm:readings
      REDIS_URL: redis://redis:6379/0
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: C:\Users\rodri\source\25-26\teamproject\MTS3-MCTE-Team-Project-Energy-G1\apps\backend\models
        target: /app/models
        read_only: true
        bind: {}
      - type: bind
        source: C:\Users\rodri\source\25-26\teamproject\MTS3-MCTE-Team-Project-Energy-G1\apps\backend\data
        target: /app/data
        read_only: true
        bind: {}
      - type: bind
        source: C:\Users\rodri\source\25-26\teamproject\MTS3-MCTE-Team-Project-Energy-G1\apps\backend\src
        target: /app/src
        read_only: true
        bind: {}
networks:
  default:
    name: nilm-network
volumes:
  influxdb-config:
    name: mts3-mcte-team-project-energy-g1_influxdb-config
  influxdb-data:
    name: mts3-mcte-team-project-energy-g1_influxdb-data
  redis-data:
    name: mts3-mcte-team-project-energy-g1_redis-data
