
# Docker Compose for E2E Testing

services:
  # Override backend to use testing env if needed
  # backend:
  #   environment:
  #     - ENV=test

  # Add Frontend
  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  # Add Prediction Persister (The bridge we just made)
  nilm-persister:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: production
    container_name: nilm-persister-e2e
    depends_on:
      - redis
      - influxdb
    environment:
      - REDIS_HOST=redis
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET_PRED=${INFLUX_BUCKET_PRED}
    command: ["python", "-m", "app.pipeline.persister"]

  # Override Producer to use our FIXTURE instead of huge parquet
  nilm-producer:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: production
    volumes:
      - ./apps/backend/tests/fixtures/test_data.parquet:/app/test_data.parquet
    # Run faster interval for tests (0.1s)
    command: >
      sh -c "python -m app.pipeline.producer --source parquet --file /app/test_data.parquet --interval 0.1 --fast"
    profiles: [] # Remove 'testing' profile so it runs by default in e2e

  # Override Inference Service to use Test Env (activates fallback)
  nilm-inference:
    environment:
      - ENV=test

  # Test Runner (Ephemeral container to run pytest)
  e2e-tests:
    build:
      context: .
      target: test
    depends_on:
      - backend
      - nilm-persister
    environment:
      - REDIS_HOST=redis
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    # Volumes removed to rely on baked-in code/data (solves sync issues)
    # volumes:
    #   - ./apps/backend/tests:/app/tests
    working_dir: /app
    # Deps are installed in image. Just run tests.
    command: ["pytest", "tests/integration", "-v"]
    profiles:
      - test-runner
