// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getEnv } from "@/lib/env";
import { customAuthStorage } from "@/lib/authStorage";

const { supabaseUrl, supabaseAnonKey } = getEnv();

// Fallback to placeholder to prevent crash if env vars missing
const SUPABASE_URL = supabaseUrl || "https://placeholder.supabase.co";
const SUPABASE_ANON_KEY = supabaseAnonKey || "placeholder";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    auth: {
      storage: customAuthStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: "pkce",
    },
  },
);
